
% 3 bands from the same genre
% 1 - King Imagine, electronic/ambient/soundtrack
% 2 - Livio Amato, ambient/soundscape (skipped piano only albums)
% 3 - Soularflair, deep electronic/soundscape

B1 = ["https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/AXID/King_Imagine_-_03_-_GM_45.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Inside/King_Imagine_-_05_-_Ivy.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Inside/King_Imagine_-_06_-_Glass-Wool.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Inside/King_Imagine_-_03_-_Pacer.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Next_Nowhereexe/King_Imagine_-_02_-_E.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Next_Nowhereexe/King_Imagine_-_03_-_Re.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Next_Nowhereexe/King_Imagine_-_07_-_Nowhere.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Stand_Alone_Complex/King_Imagine_-_06_-_Green_Sand.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Stand_Alone_Complex/King_Imagine_-_10_-_Moon_Sonata.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Stand_Alone_Complex/King_Imagine_-_09_-_Wonky_Clouds.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Stand_Alone_Complex/King_Imagine_-_04_-_lliquid.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Tapes_4_ALL/King_Imagine_-_02_-_Tape_For_CIA.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Tapes_4_ALL/King_Imagine_-_03_-_Tape_For_FBI.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Tapes_4_ALL/King_Imagine_-_05_-_Tape_For_DZA.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Tapes_4_ALL/King_Imagine_-_06_-_Tape_For_GPK.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Tapes_4_ALL/King_Imagine_-_01_-_Tape_For_WWA.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Stand_Alone_Complex/King_Imagine_-_03_-_Furry.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Stand_Alone_Complex/King_Imagine_-_01_-_Stand_Alone_Complex.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Stand_Alone_Complex/King_Imagine_-_07_-_Maple_Leaf.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Stand_Alone_Complex/King_Imagine_-_02_-_Dew_In_A_Cobweb.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Next_Nowhereexe/King_Imagine_-_08_-_Foot_Mood_And_Wind.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Next_Nowhereexe/King_Imagine_-_06_-_Gentle_Away.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Next_Nowhereexe/King_Imagine_-_01_-_Coffee.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Inside/King_Imagine_-_07_-_Trip_Fantasia.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Inside/King_Imagine_-_01_-_35_C.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/Inside/King_Imagine_-_02_-_Box_With_Four_Tunes.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/AXID/King_Imagine_-_07_-_Workshop.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/AXID/King_Imagine_-_06_-_Dixa.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/AXID/King_Imagine_-_01_-_Morning_Explorer.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Southern_Citys_Lab/King_Imagine/AXID/King_Imagine_-_02_-_Wrong_Way_to_Know.mp3"];

B2 = ["https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/The_Priestess/Livio_Amato_-_04_-_Sarahs_dream.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Perception/Livio_Amato_-_03_-_Beyond_the_feel.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Perception/Livio_Amato_-_02_-_Of_love_and_hate.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Perception/Livio_Amato_-_01_-_The_long_journey.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Collected_Thoughts/Livio_Amato_-_09_-_Pages_of_Life.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Collected_Thoughts/Livio_Amato_-_05_-_Night_Hills.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Collected_Thoughts/Livio_Amato_-_06_-_Rodolfos_Death.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Collected_Thoughts/Livio_Amato_-_10_-_Sensitivity.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Collected_Thoughts/Livio_Amato_-_07_-_Notturno.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Collected_Thoughts/Livio_Amato_-_16_-_Wilhelmina.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Collected_Thoughts/Livio_Amato_-_13_-_Infinity.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Collected_Thoughts/Livio_Amato_-_08_-_The_Nightflight.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Collected_Thoughts/Livio_Amato_-_04_-_Rain_Suite.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Perception/Livio_Amato_-_04_-_In_your_eyes.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Perception/Livio_Amato_-_06_-_Perception.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/The_Priestess/Livio_Amato_-_06_-_Heresya.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/The_Priestess/Livio_Amato_-_03_-_The_Knights.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/The_Priestess/Livio_Amato_-_07_-_Ancestral.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/The_Priestess/Livio_Amato_-_01_-_Opening_to_the_Priestess.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/OltreAmare/Livio_Amato_-_11_-_Revelations.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/OltreAmare/Livio_Amato_-_08_-_The_doubt.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/OltreAmare/Livio_Amato_-_13_-_Gone.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/OltreAmare/Livio_Amato_-_16_-_A_brief_end.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/OltreAmare/Livio_Amato_-_15_-_Epilogue.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/OltreAmare/Livio_Amato_-_05_-_Morning_after.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/OltreAmare/Livio_Amato_-_04_-_Midnight_in_Montiglio.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/OltreAmare/Livio_Amato_-_03_-_A_part_of_you.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Collected_Thoughts/Livio_Amato_-_14_-_Of_Love_and_Hate.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/Collected_Thoughts/Livio_Amato_-_15_-_In_Your_Eyes.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Livio_Amato/The_Priestess/Livio_Amato_-_08_-_The_awakening.mp3"];

B3 = ["https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_01_-_Industrial_1_tense_-_144bpm.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_03_-_Industrial_3_mid-pace_abrasive_noisy_-_118bpm.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_05_-_Industrial_5_repetitive_suit_action_sequence_-_202bpm.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_07_-_Industrial_7_building_lurching_epic_-_95bpm.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_10_-_Cue_1_-_Dark_dance-Unease_Digital_Soul.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_12_-_Cue_3_-_Dark-Minimal-Pumping_Digital_Soul.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_14_-_Cue_2_-_Dark_dance_Pulse.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_16_-_Cue_2_-_Deep-Minimal-Brooding-Scary_Infinity_Ad_Nauseum.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_18_-_Cue_2_-_Slow-Unease-Confusion-Piano_Brass_Clarinet_Cello_Once_More_Into_The_Fray.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_19_-_Cue_3c_-_Ghostly-Spooky-Building-Synth_only_Infinity_Ad_Nauseum.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_21_-_Cue_6_-_Ghostly-Somewhat_Sad-Scary-HipHop_Infinity_Ad_Nauseum.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_23_-_Cue_7b_-_Dark-Threatening-Scary-HipHop-no_guitar_Infinity_Ad_Nauseum.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_25_-_Cue_8b_-_Dark-Threatening-Scary-Sad-no_drums_Infinity_Ad_Nauseum.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_27_-_Cue_3_-_Tension-Drama-Accelerating-Piano_Drums_Cello_Brass_Once_More_Into_The_Fray.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_29_-_Cue_5_-_Fury-Anger-Confusion-Chaos-Heavy-Piano_Metal_Once_More_Into_The_Fray.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_31_-_Cue_2_-_Voices-Tense-Ghostly-Harrowing_A_Darker_Side_To_Light.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_33_-_Cue_2a_-_Spacey-Scary-Dark-no_drums_No_Light_Without_Shadow.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_35_-_Cue_3_-_Tension-Drama-Unease-like_Dead_Can_Dance_Outcasts_Of_The_Waking_World.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_37_-_Cue_1_-_Dark-Ghostly-Slow_building-Tension_The_Inner_Circles_Of_Madness.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_39_-_Cue_1_-_Montage-Understated-Focus_Lets_Do_This.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_40_-_Cue_1a_-_Spooky-Dark-Delay-Western-Guitar_Something_Broken_Somewhere.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_42_-_Cue_4_-_Darker-Somewhat_Sad-Edgy-Ghostly-Dance_Something_Broken_Somewhere-Asendent_Remix.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_44_-_Cue_1b_-_Pink_Floyd-esque_Synth_drone-with_drums_and_bass_Soul_Purpose.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_46_-_Cue_4_-_African_or_Jungle_vibe-Darker_feel_Soul_Purpose.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_48_-_Cue_4_-_Dark-Brooding-Slow_building-Jangly_delayed_guitar__all_instruments_The_Everlasting_Embrace.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_50_-_Cue_1_-_Darker-Jazzy_Piano-_bass_-_drums_The_Mask_Of_Sanity.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_52_-_Cue_4_-_Dark-Ghostly-voices_only_The_Mask_Of_Sanity.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_54_-_Cue_1b_-_Tension-Drama-Building-Film_Trailer-Cello_and_more_with_drums_Trailer_For_A_Nonexistent_Film_1.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_56_-_Cue_2_-_Dark-Tense-Dramatic-Building-Film_trailer_Trailer_For_A_Nonexistent_Film_3.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Soularflair/CUES_for_film_TV_games_etc_DARK/Soularflair_-_58_-_Cue_1_-_Dark-Spooky-Echo-Guitar_only_The_Scream_That_Shakes_The_Soul.mp3"];

Bu = [B1; B2; B3];

% 3 bands from 3 genres

% A - The Tudor Consort, choral
A1 = ["https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Stabat_Mater_-_Domenico_Scarlatti/The_Tudor_Consort_-_01_-_Stabat_Mater.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Stabat_Mater_-_Domenico_Scarlatti/The_Tudor_Consort_-_02_-_Cujus_animam_gementem.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Stabat_Mater_-_Domenico_Scarlatti/The_Tudor_Consort_-_03_-_Quis_non_posset.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Stabat_Mater_-_Domenico_Scarlatti/The_Tudor_Consort_-_05_-_Sancta_mater_istud_agas.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Stabat_Mater_-_Domenico_Scarlatti/The_Tudor_Consort_-_07_-_Juxta_crucem.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Stabat_Mater_-_Domenico_Scarlatti/The_Tudor_Consort_-_08_-_Inflammatus.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Stabat_Mater_-_Domenico_Scarlatti/The_Tudor_Consort_-_09_-_Fac_ut_animae.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Stabat_Mater_-_Domenico_Scarlatti/The_Tudor_Consort_-_10_-_Amen.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Giovanni_Animuccia_Missa_Victimae_Paschali_Laudes/The_Tudor_Consort_-_02_-_Introit_-_Resurrexi_et_Adhuc_Tecum_Sum.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Giovanni_Animuccia_Missa_Victimae_Paschali_Laudes/The_Tudor_Consort_-_03_-_Kyrie_Eleison.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Giovanni_Animuccia_Missa_Victimae_Paschali_Laudes/The_Tudor_Consort_-_04_-_Gloria_in_Excelsis_Deo.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Giovanni_Animuccia_Missa_Victimae_Paschali_Laudes/The_Tudor_Consort_-_09_-_Sequence_-_Victimae_Paschali_Laudes.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Giovanni_Animuccia_Missa_Victimae_Paschali_Laudes/The_Tudor_Consort_-_10_-_Gospel_-_Maria_Magdalene_et_Maria_Jacobi.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Giovanni_Animuccia_Missa_Victimae_Paschali_Laudes/The_Tudor_Consort_-_11_-_Credo_in_Unum_Deum.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Giovanni_Animuccia_Missa_Victimae_Paschali_Laudes/The_Tudor_Consort_-_13_-_Offertory_-_Terra_Tremuit.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Giovanni_Animuccia_Missa_Victimae_Paschali_Laudes/The_Tudor_Consort_-_14_-_Sursum_Corda.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Giovanni_Animuccia_Missa_Victimae_Paschali_Laudes/The_Tudor_Consort_-_15_-_Sanctus.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Giovanni_Animuccia_Missa_Victimae_Paschali_Laudes/The_Tudor_Consort_-_19_-_Agnus_Dei_I.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Giovanni_Animuccia_Missa_Victimae_Paschali_Laudes/The_Tudor_Consort_-_20_-_Agnus_Dei_II.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Live_in_Concert/The_Tudor_Consort_-_01_-_Orlando_Gibbons_-_Out_of_the_Deep.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Live_in_Concert/The_Tudor_Consort_-_02_-_William_Byrd_-_Civitas_Sancti_Tui.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Live_in_Concert/The_Tudor_Consort_-_03_-_Palestrina_-_Sicut_Lilium_Introduxit_Me_Rex.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Live_in_Concert/The_Tudor_Consort_-_04_-_Jacobus_Clemens_non_Papa_-_Ego_Flos_Campi.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Live_in_Concert/The_Tudor_Consort_-_06_-_Alonso_Lobo_-_Versa_est_in_Luctum.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Live_in_Concert/The_Tudor_Consort_-_07_-_Thomas_Tallis_-_Lamentations_I.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Live_in_Concert/The_Tudor_Consort_-_09_-_Annibale_Stabile_-_Apollinaris_Inclyti.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Live_in_Concert/The_Tudor_Consort_-_10_-_Alfonso_Ferrabosco_-_Lamentations_III.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Renaissance_influences_-_Pizzetti_Messa_di_Requiem__Palestrina_Missa_Sicut_lilium_inter_spinas/The_Tudor_Consort_-_01_-_Palestrina_-_Sicut_lilium_inter_spinas.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Renaissance_influences_-_Pizzetti_Messa_di_Requiem__Palestrina_Missa_Sicut_lilium_inter_spinas/The_Tudor_Consort_-_02_-_Palestrina_-_Kyrie_-_Missa_Sicut_lilium_inter_spinas.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Tudor_Consort/Renaissance_influences_-_Pizzetti_Messa_di_Requiem__Palestrina_Missa_Sicut_lilium_inter_spinas/The_Tudor_Consort_-_03_-_Palestrina_-_Gloria_-_Missa_Sicut_lilium_inter_spinas.mp3"];

% Derek Clegg - folk, acoustic, indie
A2 = ["https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_01_-_The_Way_I_Feel.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_02_-_Our_Love_Is_Rich_Enough.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_03_-_Peculiar.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_04_-_Is_Real.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_05_-_It_Aint_This_Bed.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_06_-_Help_Desk.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_07_-_Working_For_The_County.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_08_-_Life_and_Times.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_09_-_My_Word.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_10_-_Selfish.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_11_-_Good_Graces.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_12_-_Bed_of_Weeds.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_13_-_Unfair_To_Me.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_14_-_I_Have_You.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Good_Graces/Derek_Clegg_-_15_-_Never_Really_Change.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/blocSonic/Derek_Clegg/Borish_Songs_For_L/Derek_Clegg_-_01_-_Its_Worth_It.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/blocSonic/Derek_Clegg/Borish_Songs_For_L/Derek_Clegg_-_02_-_Last_a_Day.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/blocSonic/Derek_Clegg/Borish_Songs_For_L/Derek_Clegg_-_03_-_Paper_Aeroplane.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/blocSonic/Derek_Clegg/Borish_Songs_For_L/Derek_Clegg_-_04_-_Straight_Towards_The_Sun.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/blocSonic/Derek_Clegg/Borish_Songs_For_L/Derek_Clegg_-_05_-_Night_Sweats.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/blocSonic/Derek_Clegg/Borish_Songs_For_L/Derek_Clegg_-_06_-_True_Love.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/blocSonic/Derek_Clegg/Borish_Songs_For_L/Derek_Clegg_-_07_-_Sleeping_Pills.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/blocSonic/Derek_Clegg/Borish_Songs_For_L/Derek_Clegg_-_08_-_Helping_Hand.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/blocSonic/Derek_Clegg/Borish_Songs_For_L/Derek_Clegg_-_09_-_Someone_Else.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/blocSonic/Derek_Clegg/Borish_Songs_For_L/Derek_Clegg_-_10_-_Strangers.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/blocSonic/Derek_Clegg/Borish_Songs_For_L/Derek_Clegg_-_11_-_Borish.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/blocSonic/Derek_Clegg/Borish_Songs_For_L/Derek_Clegg_-_12_-_What_Im_Putting_Down.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Faces_re-release/Derek_Clegg_-_01_-_Faces.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Faces_re-release/Derek_Clegg_-_02_-_The_Lean.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Derek_Clegg/Faces_re-release/Derek_Clegg_-_03_-_Ahead_Of_The_Crowd.mp3"];

A3 = B1;

Au = [A1; A2; A3];

% 3 genres, different bands
% CHORAL // a: Tudor Consort, b: MIT concert choir, c: NYC Georgian choir
C1 = [A1(1:10,:)
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Oddio_Overplay/MIT_Concert_Choir/Carmina_Burana/MIT_Concert_Choir_-_01_-_O_Fortuna.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Oddio_Overplay/MIT_Concert_Choir/Carmina_Burana/MIT_Concert_Choir_-_02_-_Fortune_planto_vulnera.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Oddio_Overplay/MIT_Concert_Choir/Carmina_Burana/MIT_Concert_Choir_-_03_-_Veris_leta_facies.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Oddio_Overplay/MIT_Concert_Choir/Carmina_Burana/MIT_Concert_Choir_-_04_-_Omnia_sol_temperat.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Oddio_Overplay/MIT_Concert_Choir/Carmina_Burana/MIT_Concert_Choir_-_05_-_Ecce_gratum.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Oddio_Overplay/MIT_Concert_Choir/Carmina_Burana/MIT_Concert_Choir_-_07_-_Floret_Silva.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Oddio_Overplay/MIT_Concert_Choir/Carmina_Burana/MIT_Concert_Choir_-_08_-_Chramer_gip_die_varwe_mir.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Oddio_Overplay/MIT_Concert_Choir/Carmina_Burana/MIT_Concert_Choir_-_09_-_Swaz_hie_gat_umbe_-_Chume_chum_geselle_min.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Oddio_Overplay/MIT_Concert_Choir/Carmina_Burana/MIT_Concert_Choir_-_11_-_Estuans_interius.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Oddio_Overplay/MIT_Concert_Choir/Carmina_Burana/MIT_Concert_Choir_-_12_-_Olim_lacus_colueram.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Supruli/Live_at_2018_Golden_Festival/Supruli_-_01_-_Meskhuri_Mravalzhamieri.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Supruli/Live_at_2018_Golden_Festival/Supruli_-_02_-_Imeruli_Alilo.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Supruli/Live_at_2018_Golden_Festival/Supruli_-_03_-_Chaguna.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Supruli/Live_at_2018_Golden_Festival/Supruli_-_04_-_Lashkrad_Tsasvla.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Supruli/Live_at_2018_Golden_Festival/Supruli_-_05_-_Barbal_Dolash.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Supruli/Live_at_2018_Golden_Festival/Supruli_-_06_-_Qumuris_Naduri.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Supruli/Live_at_the_2016_Golden_Festival/Supruli_-_02_-_Ocheshkhvei.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Supruli/Live_at_the_2016_Golden_Festival/Supruli_-_04_-_Miqvars_Amperad.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Supruli/Live_at_the_2016_Golden_Festival/Supruli_-_06_-_Odila.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Supruli/Live_at_the_2016_Golden_Festival/Supruli_-_07_-_Mokle_Mravalzhamieri_Kartli-Kakheti.mp3"];

% balkan big band
C2 = ["https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Great_Circles/Live_at_2018_Golden_Festival/Great_Circles_-_01_-_Winter_Within.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Great_Circles/Live_at_2018_Golden_Festival/Great_Circles_-_02_-_Glass_EyeSnow_Globe.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Great_Circles/Live_at_2018_Golden_Festival/Great_Circles_-_03_-_Big_Weather.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Great_Circles/Live_at_2018_Golden_Festival/Great_Circles_-_04_-_Pesna_Bez_Zborovi.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Ziklibrenbib/Brazzmatazz/HUA_/Brazzmatazz_-_03_-_3_Zopje.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Ziklibrenbib/Brazzmatazz/Turbolence/Brazzmatazz_-_02_-_Draaikolk.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Ziklibrenbib/Brazzmatazz/Turbolence/Brazzmatazz_-_08_-_Helping_Hands.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Ziklibrenbib/Brazzmatazz/Turbolence/Brazzmatazz_-_10_-_Mezcal_Y_Sangrita.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Ziklibrenbib/Brazzmatazz/Turbolence/Brazzmatazz_-_05_-_Misantropisch_Zwemparadijs.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/oek_Nation/Live_at_the_2014_Golden_Festival/oek_Nation_-_01_-_Xelianov.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/oek_Nation/Live_at_the_2014_Golden_Festival/oek_Nation_-_02_-_Ekxtra.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/oek_Nation/Live_at_the_2014_Golden_Festival/oek_Nation_-_03_-_Esma_Kirigili.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/oek_Nation/Live_at_the_2014_Golden_Festival/oek_Nation_-_04_-_Zajkova.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/oek_Nation/Live_at_the_2014_Golden_Festival/oek_Nation_-_05_-_Firdizjen.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/oek_Nation/Live_at_the_2014_Golden_Festival/oek_Nation_-_06_-_Krushka.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/oek_Nation/Live_at_2018_Golden_Festival/oek_Nation_-_02_-_Bokijev.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/oek_Nation/Live_at_2018_Golden_Festival/oek_Nation_-_04_-_Lacin.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/oek_Nation/Live_at_2018_Golden_Festival/oek_Nation_-_05_-_Dobrivoj.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/oek_Nation/Live_at_2018_Golden_Festival/oek_Nation_-_06_-_Reka_Zelija.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Harris_Brothers_Balkan_Band/Live_at_the_2014_Golden_Festival/Harris_Brothers_Balkan_Band_-_01_-_Lesnoto_Medley.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Harris_Brothers_Balkan_Band/Live_at_the_2014_Golden_Festival/Harris_Brothers_Balkan_Band_-_02_-_Balada_Andjeo_Cuvar.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Harris_Brothers_Balkan_Band/Live_at_the_2014_Golden_Festival/Harris_Brothers_Balkan_Band_-_03_-_Cage_Sutkarja.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Harris_Brothers_Balkan_Band/Live_at_the_2014_Golden_Festival/Harris_Brothers_Balkan_Band_-_04_-_Jove_Male_Mome.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Harris_Brothers_Balkan_Band/Live_at_the_2014_Golden_Festival/Harris_Brothers_Balkan_Band_-_05_-_Dgelan_Dades_Laredo_Cocek.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Harris_Brothers_Balkan_Band/Live_at_2018_Golden_Festival/Harris_Brothers_Balkan_Band_-_01_-_Vranjanka.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Harris_Brothers_Balkan_Band/Live_at_2018_Golden_Festival/Harris_Brothers_Balkan_Band_-_02_-_Gorno_Selsko_Oro.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Harris_Brothers_Balkan_Band/Live_at_2018_Golden_Festival/Harris_Brothers_Balkan_Band_-_03_-_Olympiski.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Harris_Brothers_Balkan_Band/Live_at_2018_Golden_Festival/Harris_Brothers_Balkan_Band_-_04_-_Baba_Djurdja.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Harris_Brothers_Balkan_Band/Live_at_the_2017_Golden_Festival/Harris_Brothers_Balkan_Band_-_04_-_Dospatsko_Oro.mp3"
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Harris_Brothers_Balkan_Band/Live_at_the_2017_Golden_Festival/Harris_Brothers_Balkan_Band_-_01_-_Vranjanka.mp3"];

% ambient/soundscape/electronic
C3 = [B1(1:10,1); B2(1:10,1); B3(1:10,1)];

Cu = [C1; C2; C3];

save('urls.mat','Au','Bu','Cu')
